name: Weekly Cleanup
permissions:
  contents: write

on:
  schedule:
    - cron: "30 1 1,15 * *"  # Runs on 1st & 15th at 1:30am
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Count input files
      id: count
      run: |
        num_files=$(find input -maxdepth 1 -type f -name '*-AlertBook.csv' | wc -l)

        # If there are 1 or fewer files, exit the script
        if [ "$num_files" -le 1 ]; then
          echo "Exiting as there are 1 or fewer -AlertBook.csv files in the input directory."
          echo "skip=true" >> $GITHUB_ENV
        else
          echo "skip=false" >> $GITHUB_ENV
        fi
      
    - name: Delete old files
      if: ${{ env.skip != 'true' }}
      run: |
        find input -maxdepth 1 -type f -name '*-AlertBook.csv' -printf "%T@ %p\n" |
          sort -n | head -n -1 | cut -d ' ' -f 2- |
          while IFS= read -r file; do
            echo "Deleting: $file"
            git rm "$file"
          done

    - name: Commit changes
      if: ${{ env.skip != 'true' }}
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git commit -m "Cleanup: Remove all but 1 latest input files"
        git push https://${{ secrets.NEFKITTY_PAT }}@github.com/allie-fowler/nefarious-kitten.git HEAD:main
