name: Scrub Alchem exports
on: 
  pull_request: 
  workflow_dispatch:
  push:
    paths:
      - 'input/*.sym'
      - 'scripts/alchem/clean_alchem_exports.ps1'
jobs:
  cleanup-aisle-7:
    name: Scrub Alchem exports
    runs-on: ubuntu-latest
    steps:
    - name: "Check out repository code"
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: "Clean Up and Down recipe exports from Alchem"
      shell: pwsh
      run: |
        scripts/alchem/clean_alchem_exports.ps1   
