name: Weekly Cleanup

on:
  schedule:
    - cron: "0 0 * * 0"  # Runs every Sunday at midnight
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Delete old files
      run: |
        find input -maxdepth 1 -type f -name '*-AlertBook.csv' -printf "%T@ %p\n" |
          sort -n | head -n -1 | cut -d ' ' -f 2- |
          while IFS= read -r file; do
            echo "Deleting: $file"
            #rm "$file"
          done

    - name: Commit changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add -A
        git commit -m "Cleanup: Remove old files"
        git push
