name: Get recent ToS recipe hits
on: 
  pull_request: 
  workflow_dispatch:
  push:
    paths:
      - 'input/*AlertBook.csv'
      - 'tos/recent_recipes_from_tos.ps1'

jobs:
  get-hits:
    name: Recipe / Moses hits
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Run the recent_recipes_from_tos.ps1 script
      shell: pwsh
      run: |
        scripts/tos/recent_recipes_from_tos.ps1
