name: Test PowerShell on Ubuntu
on: push

jobs:
  pester-test:
    name: Pester test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Perform a Pester test from the command-line
        shell: pwsh
        run: Test-Path 20*-AlertBook.csv | Should -Be $true
      - name: Perform a Pester test on the recent_recipes_from_tos.ps1 file
        shell: pwsh
        run: |
          Invoke-Pester tests/test_recent_tos_recipes.ps1 tests/testdata/2023-05-13-AlertBook.csv -Passthru
      - name: Run the recent_recipes_from_tos.ps1 script
        run: |
          Set-PSDebug -Trace 1
          pwsh tests/test_recent_tos_recipes.ps1
          Set-PSDebug -Off
